{
 "title": "Pulsar Broker Metrics",
 "tags": [
  "pulsar",
  "broker"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(pulsar_broker_in_messages_total, cluster)"
   },
   {
    "name": "broker",
    "label": "Broker",
    "query": "label_values(pulsar_broker_in_messages_total{cluster=\"$cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Broker Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Brokers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=\"pulsar-broker\", cluster=\"$cluster\", instance=~\"$broker\"} == 1)"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pulsar_broker_connections{cluster=\"$cluster\", instance=~\"$broker\"})"
    }
   ]
  },
  {
   "title": "Average Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(time() - process_start_time_seconds{job=\"pulsar-broker\", cluster=\"$cluster\", instance=~\"$broker\"})"
    }
   ]
  },
  { "title": "Message Traffic by Broker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Message Rate by Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(pulsar_broker_in_messages_total{cluster=\"$cluster\", instance=~\"$broker\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} - In"
    },
    {
     "expr": "sum(rate(pulsar_broker_out_messages_total{cluster=\"$cluster\", instance=~\"$broker\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} - Out"
    }
   ]
  },
  {
   "title": "Throughput by Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(pulsar_broker_in_bytes_total{cluster=\"$cluster\", instance=~\"$broker\"}[5m])) by (instance) / 1024 / 1024",
     "legendFormat": "{{instance}} - In"
    },
    {
     "expr": "sum(rate(pulsar_broker_out_bytes_total{cluster=\"$cluster\", instance=~\"$broker\"}[5m])) by (instance) / 1024 / 1024",
     "legendFormat": "{{instance}} - Out"
    }
   ]
  },
  { "title": "Topic Management", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Topics per Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "pulsar_broker_topics{cluster=\"$cluster\", instance=~\"$broker\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Topic Load Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "rate(pulsar_broker_topic_load_times_sum{cluster=\"$cluster\", instance=~\"$broker\"}[5m]) / rate(pulsar_broker_topic_load_times_count{cluster=\"$cluster\", instance=~\"$broker\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connections per Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "pulsar_broker_connections{cluster=\"$cluster\", instance=~\"$broker\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Replication & Load Balancing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Replication Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(pulsar_broker_replication_rate_in{cluster=\"$cluster\", instance=~\"$broker\"}[5m])",
     "legendFormat": "{{instance}} - In"
    },
    {
     "expr": "rate(pulsar_broker_replication_rate_out{cluster=\"$cluster\", instance=~\"$broker\"}[5m])",
     "legendFormat": "{{instance}} - Out"
    }
   ]
  },
  {
   "title": "Load Balance Weight",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "pulsar_broker_load_balance_weight{cluster=\"$cluster\", instance=~\"$broker\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}