{
 "title": "Topic & Namespace Metrics",
 "tags": [
  "pulsar",
  "topic",
  "namespace"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(pulsar_broker_in_messages_total, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(pulsar_broker_in_messages_total{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(pulsar_broker_in_messages_total{cluster=\"$cluster\", namespace=~\"$namespace\"}, topic)"
   }
  ]
 },
 "panels": [
  { "title": "Topic Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Topics",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by () (group by (topic) (pulsar_broker_in_messages_total{cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"}))"
    }
   ]
  },
  {
   "title": "Active Namespaces",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by () (group by (namespace) (pulsar_broker_in_messages_total{cluster=\"$cluster\", namespace=~\"$namespace\"}))"
    }
   ]
  },
  {
   "title": "Total Producers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pulsar_broker_producers{cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Total Consumers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pulsar_broker_consumers{cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"})"
    }
   ]
  },
  { "title": "Message Traffic by Topic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Top 10 Topics - Message Rate In",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "topk(10, sum(rate(pulsar_broker_in_messages_total{cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"}[5m])) by (topic))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Top 10 Topics - Message Rate Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "topk(10, sum(rate(pulsar_broker_out_messages_total{cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"}[5m])) by (topic))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Throughput by Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Throughput In by Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(pulsar_broker_in_bytes_total{cluster=\"$cluster\", namespace=~\"$namespace\"}[5m])) by (namespace) / 1024 / 1024",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Throughput Out by Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(pulsar_broker_out_bytes_total{cluster=\"$cluster\", namespace=~\"$namespace\"}[5m])) by (namespace) / 1024 / 1024",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Storage & Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Top 10 Topics - Storage Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "topk(10, pulsar_broker_storage_size{cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"} / 1024 / 1024)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Replication Backlog by Topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(pulsar_broker_replication_back_log{cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topic Statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(pulsar_broker_in_messages_total{cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"}[5m])) by (topic)"
    },
    {
     "expr": "sum(rate(pulsar_broker_out_messages_total{cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"}[5m])) by (topic)"
    },
    {
     "expr": "sum(pulsar_broker_producers{cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"}) by (topic)"
    },
    {
     "expr": "sum(pulsar_broker_consumers{cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"}) by (topic)"
    },
    {
     "expr": "sum(pulsar_broker_storage_size{cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"}) by (topic) / 1024 / 1024"
    }
   ]
  }
 ]
}