{
 "title": "Consumer & Subscription Metrics",
 "tags": [
  "pulsar",
  "consumer",
  "subscription"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(pulsar_broker_subscription_back_log, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(pulsar_broker_subscription_back_log{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(pulsar_broker_subscription_back_log{cluster=\"$cluster\", namespace=~\"$namespace\"}, topic)"
   }
  ]
 },
 "panels": [
  { "title": "Consumer Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Consumers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pulsar_broker_consumers{cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Total Subscriptions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by () (group by (subscription) (pulsar_broker_subscription_back_log{cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"}))"
    }
   ]
  },
  {
   "title": "Total Message Backlog",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pulsar_broker_subscription_back_log{cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Total Ack Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(pulsar_broker_subscription_msg_ack_rate{cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"}[5m]))"
    }
   ]
  },
  { "title": "Message Backlog Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Top 10 Subscriptions - Message Backlog",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "topk(10, pulsar_broker_subscription_back_log{cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"})",
     "legendFormat": "{{topic}} - {{subscription}}"
    }
   ]
  },
  {
   "title": "Message Backlog by Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(pulsar_broker_subscription_back_log{cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Consumer Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Consumer Message Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(pulsar_broker_subscription_msg_rate_out{cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"}[5m])) by (topic, subscription)",
     "legendFormat": "{{topic}} - {{subscription}}"
    }
   ]
  },
  {
   "title": "Message Acknowledgment Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(pulsar_broker_subscription_msg_ack_rate{cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"}[5m])) by (topic, subscription)",
     "legendFormat": "{{topic}} - {{subscription}}"
    }
   ]
  },
  {
   "title": "Subscription Types & Distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }
  },
  {
   "title": "Consumers per Subscription",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "pulsar_broker_consumers{cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"}",
     "legendFormat": "{{topic}} - {{subscription}}"
    }
   ]
  },
  {
   "title": "Consumer Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(pulsar_broker_subscription_throughput_out{cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"}[5m])) by (topic, subscription) / 1024 / 1024",
     "legendFormat": "{{topic}} - {{subscription}}"
    }
   ]
  },
  {
   "title": "Subscription Type Distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "count by (subscription_type) (group by (subscription_type, topic, subscription) (pulsar_broker_subscription_type{cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"}))",
     "legendFormat": "{{subscription_type}}"
    }
   ]
  },
  {
   "title": "Subscription Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "pulsar_broker_subscription_back_log{cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"}"
    },
    {
     "expr": "pulsar_broker_consumers{cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"}"
    },
    {
     "expr": "rate(pulsar_broker_subscription_msg_rate_out{cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"}[5m])"
    },
    {
     "expr": "rate(pulsar_broker_subscription_msg_ack_rate{cluster=\"$cluster\", namespace=~\"$namespace\", topic=~\"$topic\"}[5m])"
    }
   ]
  }
 ]
}