{
 "title": "JVM & System Metrics",
 "tags": [
  "pulsar",
  "jvm",
  "system"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(jvm_memory_bytes_used, cluster)"
   },
   {
    "name": "component",
    "label": "Component",
    "query": "label_values(jvm_memory_bytes_used{cluster=\"$cluster\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_memory_bytes_used{cluster=\"$cluster\", job=~\"$component\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "JVM Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average JVM Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(time() - process_start_time_seconds{cluster=\"$cluster\", job=~\"$component\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Average Thread Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(jvm_threads_current{cluster=\"$cluster\", job=~\"$component\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Average Heap Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 * jvm_memory_bytes_used{cluster=\"$cluster\", job=~\"$component\", instance=~\"$instance\", area=\"heap\"} / jvm_memory_bytes_max{cluster=\"$cluster\", job=~\"$component\", instance=~\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Average GC Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(rate(jvm_gc_collection_seconds_count{cluster=\"$cluster\", job=~\"$component\", instance=~\"$instance\"}[5m]))"
    }
   ]
  },
  { "title": "Heap Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Heap Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{cluster=\"$cluster\", job=~\"$component\", instance=~\"$instance\", area=\"heap\"} / 1024 / 1024",
     "legendFormat": "{{job}} - {{instance}} - Used"
    },
    {
     "expr": "jvm_memory_bytes_max{cluster=\"$cluster\", job=~\"$component\", instance=~\"$instance\", area=\"heap\"} / 1024 / 1024",
     "legendFormat": "{{job}} - {{instance}} - Max"
    }
   ]
  },
  {
   "title": "Heap Memory Usage %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "100 * jvm_memory_bytes_used{cluster=\"$cluster\", job=~\"$component\", instance=~\"$instance\", area=\"heap\"} / jvm_memory_bytes_max{cluster=\"$cluster\", job=~\"$component\", instance=~\"$instance\", area=\"heap\"}",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "GC Collection Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{cluster=\"$cluster\", job=~\"$component\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{job}} - {{instance}} - {{gc}}"
    }
   ]
  },
  {
   "title": "GC Pause Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{cluster=\"$cluster\", job=~\"$component\", instance=~\"$instance\"}[5m]) * 1000",
     "legendFormat": "{{job}} - {{instance}} - {{gc}}"
    }
   ]
  },
  { "title": "Thread & CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Thread Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "jvm_threads_current{cluster=\"$cluster\", job=~\"$component\", instance=~\"$instance\"}",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{cluster=\"$cluster\", job=~\"$component\", instance=~\"$instance\"}[5m]) * 100",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Process Memory (RSS)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{cluster=\"$cluster\", job=~\"$component\", instance=~\"$instance\"} / 1024 / 1024",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Non-Heap Memory & File Descriptors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 }
  },
  {
   "title": "Non-Heap Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{cluster=\"$cluster\", job=~\"$component\", instance=~\"$instance\", area=\"nonheap\"} / 1024 / 1024",
     "legendFormat": "{{job}} - {{instance}} - Used"
    },
    {
     "expr": "jvm_memory_bytes_max{cluster=\"$cluster\", job=~\"$component\", instance=~\"$instance\", area=\"nonheap\"} / 1024 / 1024",
     "legendFormat": "{{job}} - {{instance}} - Max"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "process_open_fds{cluster=\"$cluster\", job=~\"$component\", instance=~\"$instance\"}",
     "legendFormat": "{{job}} - {{instance}} - Open"
    },
    {
     "expr": "process_max_fds{cluster=\"$cluster\", job=~\"$component\", instance=~\"$instance\"}",
     "legendFormat": "{{job}} - {{instance}} - Max"
    }
   ]
  }
 ]
}